name: New azimuth action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: The azimuth action
    steps:
      - name: Deploy to azimuth
        id: hello
        uses: GiorgioNunzi/AzimuthGitHubAction@main
        with:
          endpoint: "digifact.aurubis.com"
          username: "staging@"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
