name: New azimuth action
on: [push]

jobs:
  azimuth:
    runs-on: ubuntu-latest
    name: Deploy to azimuth
    steps:
      - name: Deploy to azimuth - step
        id: deploy_to_azimuth_step
        uses: GiorgioNunzi/AzimuthGitHubAction@main
        with:
          endpoint: "https://digifact.aurubis.com"
          username: "${{ secrets.AZ_USERNAME }}"
          password: "${{ secrets.AZ_PASSWORD }}
