name: New azimuth action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: The action to deploy to azimuth
    steps:
      - name: Deploy to azimuth
        id: azimuth
        uses: GiorgioNunzi/AzimuthGitHubAction@main
        with:
          endpoint: "https://digifact.aurubis.com"
          username: "staging@"
